# fly.toml app configuration file generated for praktyk-api on 2023-08-27T16:04:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "praktyk-api"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
